import type { Metadata } from 'next';
import Header from '@/components/common/Header/Header';
import StyledComponentsRegistry from '@/styles/registry';
import ReactQueryProvider from './ReactQueryProvider';

interface Props {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
